name: twarz
description: Project of "Non Verbal Behaviour" for the Master's Course of HCI in Trento

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0-nullsafety.0
  camera: ^0.9.4+3
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  permission_handler: ^8.2.5
  radar_chart: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter:
  uses-material-design: true
